FROM node:22-alpine

WORKDIR /app

# Instala apenas dependências primeiro (melhor cache)
COPY package.json package-lock.json ./
RUN npm ci

# Copia o restante do código
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
